version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      lint-tools:
        patterns:
          - "ruff"
          - "prek"
  - package-ecosystem: "pre-commit"
    directory: "/"
    schedule:
      interval: "daily"
